version: '{build}'

build_script:
- ps: |
    $ErrorActionPreference="Stop"

    dir C:\projects

    Start-FileDownload https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip -FileName C:\projects\sqfs43-win32.zip

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\projects\sqfs43-win32.zip", "C:\projects\usr\bin")

test_script:
- cmd: |
    dir C:\

    set PATH=C:\Ruby241\bin;C:\projects\usr\bin;%PATH%

    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64_x86

    where mksquashfs

    mksquashfs -version

    where ruby

    ruby --version

    where gem

    gem --version

    gem install C:\projects\ruby-compiler\ruby\gems\bundler-*.gem --force --local --no-rdoc --no-ri 

    where bundle

    bundle --version

    ruby tests\ruby-compiler
