#!/usr/bin/env ruby

# Copyright (c) 2017 Minqi Pan <pmq2001@gmail.com>
# 
# This file is part of Ruby Compiler, distributed under the MIT License
# For full terms see the included LICENSE file

require 'shellwords'
require 'fileutils'

puts `git clone --depth 1 https://github.com/ruby-china/homeland.git`
raise 'git failed' unless $?.success?
Dir.chdir('homeland')

outpath = File.expand_path((Gem.win_platform? ? 'a.exe' : 'a.out'), Dir.pwd)
FileUtils.rm_f(outpath)

if ENV['APPVEYOR']
  lines = File.read("Gemfile").split("\n")
  File.open("Gemfile", "w") do |f|
    f.puts 'source "http://rubygems.org"'
    lines.each do |line|
      unless line =~ /^\s*source\s+/
        f.puts line
      end
    end
  end
  lines = File.read("Gemfile.lock").split("\n")
  File.open("Gemfile.lock", "w") do |f|
    lines.each_with_index do |line, index|
      if 1 == index
        f.puts ' remote: http://rubygems.org/'
      else
        f.puts line
      end
    end
  end
end

pid = spawn("ruby ../bin/rubyc puma")
pid, status = Process.wait2(pid)
raise "Failed running nodec for homeland" unless status.success?

raise unless File.exist?(outpath)
raise unless File.size(outpath) >= 10_000_000

if Gem.win_platform?
  outpath = %Q{"#{outpath}"}
else
  File.chmod(0777, outpath)
  outpath = Shellwords.escape(outpath)
end
