#!/usr/bin/env ruby

# Copyright (c) 2017 Minqi Pan <pmq2001@gmail.com>
# 
# This file is part of Ruby Compiler, distributed under the MIT License
# For full terms see the included LICENSE file

require 'shellwords'
require 'fileutils'

Dir.chdir(File.expand_path('../..', __FILE__))

unless Dir.exist?('node-compiler')
  puts `git clone --depth 1 https://github.com/pmq20/node-compiler.git`
  raise 'git failed' unless $?.success?
end
Dir.chdir('node-compiler')

outpath = File.expand_path((Gem.win_platform? ? 'a.exe' : 'a.out'), Dir.pwd)
FileUtils.rm_f(outpath)

pid = spawn("ruby ../bin/rubyc bin/nodec")
pid, status = Process.wait2(pid)
raise "Failed running rubyc for node-compiler" unless status.success?

raise unless File.exist?(outpath)
raise unless File.size(outpath) >= 10_000_000

if Gem.win_platform?
  outpath = %Q{"#{outpath}"}
else
  File.chmod(0777, outpath)
  outpath = Shellwords.escape(outpath)
end

raise unless `#{outpath} --help`.include?(%q{Compiler for Node.js that compiles your Node.js application into a single executable.})
raise unless $?.success?
raise unless `#{outpath} --node-version`.to_i >= 7
raise unless $?.success?
