# frozen_string_literal: true

source 'http://rubygems.org'

gem 'pact', '1.63.0'
gem 'pact_broker-client', '1.68.0'
gem 'pact-message', '0.11.1'
gem 'pact-mock_service', '3.11.2'
gem 'pact-provider-verifier', '1.36.1'
# gem "webrick", "1.8.1"
# gem 'rack', '>= 2.2.6'
# gem "json", "2.6.3"
# gem 'ffi'
gem 'pact_broker', '2.107.1'
gem 'pact-ffi', '0.0.3'
gem 'sucker_punch', git: 'https://github.com/pact-foundation/sucker_punch.git', ref: 'fix/rename-is-singleton-class-method-2'

## Native extension gems
gem 'pg', '1.5.3'
gem 'puma', '6.3.0'
gem 'sequel', '~> 5.71'
gem 'sqlite3', '1.6.3'
# gem "nokogiri", "1.15.3"
# gem "racc", "1.7.1"
# gem "ffi", "1.15.5"
